# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('liked', 'Liked'), ('disliked', 'Disliked')], max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vehicle_model',
            field=models.CharField(max_length=35),
        ),
        migrations.AddField(
            model_name='userrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='products.Product'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_ratings',
            field=models.ManyToManyField(related_name='ratings', through='products.UserRating', to='accounts.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=set([('product', 'user_profile')]),
        ),
    ]
